name: findr-spider

on:
  schedule:
    - cron: '0 0 * * *' # Daily at 6PM MDT
  workflow_dispatch: # Manual trigger enabled

concurrency:
  group: "spider-crawl"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Run findr Spider
        run: python findr_spider.py

      - name: Commit and Push Index
        run: |
          git config --global user.name "findr-bot"
          git config --global user.email "bot@findr.search"
          
          git add index/*.json
          
          # Avoid empty commits
          if git diff --staged --quiet; then
            echo "No changes to index."
            exit 0
          fi
          
          git commit -m "Update index: $(date +'%Y-%m-%d %I:%M %p')"
          git pull --rebase origin main
          git push
